version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    rebase-strategy: auto
    groups:
      all-dependencies:
        patterns:
          - '*'
    commit-message:
      prefix: 'deps'
      prefix-development: 'deps(dev)'
      include: scope
    labels:
      - dependencies
    open-pull-requests-limit: 5
