/**
 * SettingsView — schema-driven settings panel.
 *
 * Rows are generated by iterating `CONFIG_ROWS` from
 * `src/application/config/config-schema-rows.ts`.  Adding a new user-
 * configurable Config field requires one entry there (+ a default in
 * `config-defaults.ts`) — nothing else changes here.
 *
 * Input model:
 * - ↑/↓  (or j/k) move the row cursor
 * - Enter opens a type-appropriate prompt
 * - Esc   closes the panel (handled by global Esc → pop)
 *
 * Valid edits save immediately via `configStore.save()`.  Inline validation
 * errors appear below the row on bad input.
 */

import React, { useCallback, useEffect, useState } from 'react';
import { useViewInput } from './use-view-input.ts';
import { Box, Text } from 'ink';
import { glyphs, inkColors, spacing } from '@src/integration/ui/theme/tokens.ts';
import { ViewShell } from '@src/application/tui/components/view-shell.tsx';
import { Spinner } from '@src/application/tui/components/spinner.tsx';
import { useViewHints } from './view-hints-context.tsx';
import { getSharedDeps, getPrompt } from '@src/application/bootstrap/get-shared-deps.ts';
import type { Config } from '@src/application/config/config.ts';
import { CONFIG_DEFAULTS } from '@src/application/config/config-defaults.ts';
import { CONFIG_ROWS, type ConfigRow } from '@src/application/config/config-schema-rows.ts';
import { PromptCancelledError } from '@src/business/ports/prompt-port.ts';

const SETTINGS_HINTS = [
  { key: '↑/↓', action: 'navigate' },
  { key: 'Enter', action: 'edit' },
] as const;

function formatValue(value: unknown): string {
  if (value === null || value === undefined) return '(not set)';
  if (typeof value === 'string') return value.length === 0 ? '(empty)' : value;
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  return JSON.stringify(value);
}

export function SettingsView(): React.JSX.Element {
  useViewHints(SETTINGS_HINTS);
  const [config, setConfig] = useState<Config | null>(null);
  const [cursor, setCursor] = useState(0);
  const [error, setError] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const [editing, setEditing] = useState(false);

  useEffect(() => {
    const cancel = { current: false };
    void (async () => {
      try {
        const deps = await getSharedDeps();
        const loaded = await deps.configStore.load();
        if (!cancel.current && loaded.ok) setConfig(loaded.value);
      } catch (err) {
        if (!cancel.current) setError(err instanceof Error ? err.message : String(err));
      }
    })();
    return () => {
      cancel.current = true;
    };
  }, []);

  const saveValue = useCallback(async (row: ConfigRow, value: Config[keyof Config]): Promise<void> => {
    setError(null);
    try {
      const deps = await getSharedDeps();
      const loaded = await deps.configStore.load();
      if (!loaded.ok) throw new Error(loaded.error.message);
      // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion
      const next = { ...loaded.value, [row.key]: value } as unknown as Config;
      const saved = await deps.configStore.save(next);
      if (!saved.ok) throw new Error(saved.error.message);
      const reloaded = await deps.configStore.load();
      if (reloaded.ok) setConfig(reloaded.value);
      setNotice(`Saved ${row.label}: ${formatValue(value)}`);
    } catch (err) {
      setError(`Failed to save ${row.label}: ${err instanceof Error ? err.message : String(err)}`);
    }
  }, []);

  const startEdit = useCallback(async (): Promise<void> => {
    const row = CONFIG_ROWS[cursor];
    if (!row) return;
    setEditing(true);
    setError(null);
    setNotice(null);
    try {
      const prompt = await getPrompt();

      if (row.kind === 'select' && row.options) {
        const choices: { label: string; value: unknown }[] = row.options.map((o) => ({
          label: o.label,
          value: o.value,
        }));
        choices.unshift({ label: '(clear)', value: null });
        const picked = await prompt.select<unknown>({
          message: `Set ${row.label}`,
          choices,
          default: config?.[row.key],
        });
        await saveValue(row, picked as Config[keyof Config]);
      } else if (row.kind === 'confirm') {
        const picked = await prompt.confirm({
          message: `${row.key}?`,
          default: Boolean(config?.[row.key] ?? CONFIG_DEFAULTS[row.key]),
        });
        await saveValue(row, picked as unknown as Config[keyof Config]);
      } else {
        // 'input'
        const currentVal = config?.[row.key];
        const raw = await prompt.input({
          message: `Set ${row.label}`,
          default: currentVal !== null && currentVal !== undefined ? formatValue(currentVal) : '',
        });
        if (row.parse) {
          const parsed = row.parse(raw);
          // A string result means a validation error message, UNLESS
          // the field's valid type is string (e.g. `editor`).
          // Non-string results (number, null) are always valid.
          if (typeof parsed === 'string' && row.key !== 'editor') {
            setError(parsed);
            return;
          }
          await saveValue(row, parsed);
        } else {
          await saveValue(row, raw === '' ? null : raw);
        }
      }
    } catch (err) {
      if (err instanceof PromptCancelledError) return;
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setEditing(false);
    }
  }, [cursor, config, saveValue]);

  useViewInput((input, key) => {
    if (editing) return;
    if (key.upArrow || input === 'k') setCursor((c) => Math.max(0, c - 1));
    else if (key.downArrow || input === 'j') setCursor((c) => Math.min(CONFIG_ROWS.length - 1, c + 1));
    else if (key.return) void startEdit();
  });

  return (
    <ViewShell title="SETTINGS">
      <Box
        flexDirection="column"
        borderStyle="round"
        borderColor={inkColors.primary}
        paddingX={spacing.cardPadX}
        paddingY={0}
      >
        {config === null ? (
          <Spinner label="Loading…" />
        ) : (
          CONFIG_ROWS.map((row, i) => {
            const value = config[row.key];
            const isDefault = value === CONFIG_DEFAULTS[row.key];
            const isCursor = i === cursor;
            return (
              <Box flexDirection="column" key={row.key} marginTop={spacing.section}>
                <Box>
                  <Text color={isCursor ? inkColors.highlight : inkColors.primary} bold>
                    {isCursor ? `${glyphs.actionCursor} ` : '  '}
                    {row.label}
                  </Text>
                  <Text dimColor>{`  (${row.kind})`}</Text>
                </Box>
                <Box paddingLeft={spacing.indent}>
                  <Text dimColor>{row.description}</Text>
                </Box>
                <Box paddingLeft={spacing.indent}>
                  <Text>{formatValue(value)}</Text>
                  {isDefault ? <Text dimColor>{`  ${glyphs.inlineDot} default`}</Text> : null}
                </Box>
              </Box>
            );
          })
        )}

        {notice ? (
          <Box marginTop={spacing.section}>
            <Text color={inkColors.success}>
              {glyphs.check} {notice}
            </Text>
          </Box>
        ) : null}

        {error ? (
          <Box marginTop={spacing.section}>
            <Text color={inkColors.error}>
              {glyphs.cross} {error}
            </Text>
          </Box>
        ) : null}
      </Box>
    </ViewShell>
  );
}
